# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 19:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician', '0004_auto_20160326_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2016, 4, 11)),
        ),
    ]
