# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 19:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician', '0005_auto_20160411_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2016, 4, 14)),
        ),
    ]
