# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 03:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinician', '0006_auto_20160414_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2016, 4, 16)),
        ),
    ]
